
plugin {
    hyprscrolling {
        column_width = 0.5
        fullscreen_on_one_column = true
        focus_fit_method = 0
        explicit_column_widths = 0.25, 0.5, 0.75, 1
    }

    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1
        skip_empty = false
        gesture_distance = 300 # how far is the "max" for the gesture
    }

    hyprfocus {
        enabled = yes

        keyboard_focus_animation = shrink
        mouse_focus_animation = flash

        bezier = bezIn, 0.5,0.0,1.0,0.5
        bezier = bezOut, 0.0,0.5,0.5,1.0

        flash {
            flash_opacity = 0.7

            in_bezier = bezIn
            in_speed = 0.5

            out_bezier = bezOut
            out_speed = 3
        }

        shrink {
            shrink_percentage = 0.8

            in_bezier = bezIn
            in_speed = 0.5

            out_bezier = bezOut
            out_speed = 3
        }
    }
}
