[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
  "fetch_client_menu"
]

[monitors.placement]
"Acer".top_center_of = "Sony"

# [workspaces_follow_focus]
# max_workspaces = 5

[expose]
include_special = false

[scratchpads.stb]
animation = "fromBottom"
command = "kitty --class kitty-stb sstb"
class = "kitty-stb"
lazy = true
size = "75% 45%"

[scratchpads.stb-logs]
animation = "fromTop"
command = "kitty --class kitty-stb-logs stbLog"
class = "kitty-stb-logs"
lazy = true
size = "75% 40%"

[scratchpads.term]
animation = "fromTop"
command = "kitty --title kitty-term zsh"
class = "kitty-term"
lazy = true
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"

[scratchpads.blue]
animation = "fromTop"
command = "kitty --title bluetuith --class kitty-bluetuith -e bluetuith"
class = "kitty-bluetuith"
lazy = true
position = "64% 3%"
size = "35% 35%"
unfocus = "hide"

[scratchpads.wall]
animation = "fromTop"
command = "waypaper"
class = "waypaper-pypr"
lazy = false
# position = "75% 2%"
size = "75% 60%"
unfocus = "hide"
