
# ##############################
# ### WINDOWS AND WORKSPACES ###
# ##############################

# # See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# # See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# # Example windowrule
# windowrule = float on,class:^(kitty)$,title:^(kitty)$


# windowrule = float on,class:^(Alacritty)$,title:^(Alacritty)$
# # windowrule = colresize 1,class:helium
# windowrule = float on,move 1300 10,class:^(blueman-manager)$,border_size:0
windowrule = dim_around on,border_size 0,float on,match:title kitty-term
windowrule = dim_around off,border_size 0,float on,opacity 0.7,match:title btop-term
windowrule = border_size 0,float on on,match:title bluetuith
windowrule = border_size 0,opacity 0.7,float on,match:title Waypaper
windowrule = border_size 0,opacity 0.8,float on,match:title nwg-displays
# # windowrule = border_size 0,class:zed-editor
windowrule = pin on,content video,opacity 1 override,float on,move 1500 830,match:title ^(Picture in picture)$

layerrule = match:namespace rofi,blur on
layerrule = match:namespace waybar, blur on,xray on
# ; layerrule = blur,swaync-control-center
layerrule = match:namespace swaync-control-center,blur on
layerrule = match:namespace swaync-control-center,ignore_alpha 0

layerrule = match:namespace swaync-notification-window,blur on
layerrule = match:namespace swaync-notification-window,ignore_alpha 0

# # workspace rules for appserbird)$
windowrule = workspace 5, match:title ^(.*Discord.*)$
windowrule = workspace 5, match:title ZapZap
windowrule = workspace 5, match:title ^(.*WhatsApp.*)$

layerrule = match:namespace ashell,blur on
# # Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*

# ##############################
# ### WINDOWS AND WORKSPACES ###
# ##############################

# # See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# # See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# # Example windowrule
# # windowrule = float on,class:^(kitty)$,title:^(kitty)$


# windowrule = float on,class:^(Alacritty)$,title:^(Alacritty)$
# # windowrule = colresize 1,class:helium
# windowrule = float on,move 1300 10,class:^(blueman-manager)$,border_size:0
# windowrule = dimaround:,border_size 0,float on,title:kitty-term
# windowrule = border_size 0,float on,title:bluetuith
# windowrule = border_size 0,opacity 0.7,float on,title:Waypaper
# windowrule = border_size 0,opacity 0.8,float on,title:nwg-displays
# # windowrule = border_size 0,class:zed-editor
# windowrule = pin,content video,opacity 1 override,float on,move 1500 830,title:^(Picture in picture)$

# layerrule = blur,rofi
# layerrule = blur,waybar
# ; layerrule = blur,swaync-control-center
# ; layerrule = blur,swaync-notification-window

# # workspace rules for appserbird)$
# windowrule = workspace 9, title:^(.*Discord.*)$
# windowrule = workspace 9, title:^(.*ZapZap.*)$

# # Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*

# # Fix some dragging issues with XWayland
; windowrule = no_focus on,match:class ^$,match:title ^$,float on,fullscreen on

# # Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,float oning:1,fullscreen:0,pinned:0
